name: Deploy to Heroku

on: 
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.7
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.7.4
          bundler-cache: true
      
      - name: Setup Node 14
        uses: actions/setup-node@v3
        with: 
          node-version: 14.x

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile

      - name: Run tests
        env: 
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PG_USER: postgres
        run: |
          bin/rails db:test:setup
          bin/rails test

  Deploy:
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      needs: Test
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: "ondesk" #Must be unique in Heroku
            heroku_email: "xengawe@gmail.com"




  
